# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[graph]
# Crates.io registry
all-features = false
no-default-features = false

[advisories]
version = 2
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# Yanked crates from crates.io
yanked = "deny"
# How to handle unmaintained crate advisories
# Options: all (default), workspace, transitive, none
unmaintained = "all"

# Ignore specific advisories (use sparingly!)
ignore = [
    # Example: "RUSTSEC-2020-0001",
]

# NOTE: As of cargo-deny 0.16+, vulnerability, notice, and unsound advisories
# are all denied by default and cannot be configured to warn/allow.
# Use the 'ignore' field above to suppress specific advisories if needed.

[licenses]
version = 2
# Allow these licenses (all others are denied by default in cargo-deny 0.16+)
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "Unlicense",
    # Unicode licenses (used by ICU crates for internationalization)
    "Unicode-3.0",
    # Mozilla Public License (used by colored crate)
    "MPL-2.0",
    # Zlib license (used by foldhash)
    "Zlib",
    # Community Data License Agreement (used by webpki-roots for TLS root certificates)
    "CDLA-Permissive-2.0",
]
# NOTE: As of cargo-deny 0.16+, the 'deny' field has been removed.
# All licenses not in the 'allow' list are automatically denied.
# GPL-2.0, GPL-3.0, and AGPL-3.0 are already denied by not being in 'allow'.

# Confidence threshold for license detection
confidence-threshold = 0.8
# Allow licenses only for specific crates
exceptions = [
    # Example: { allow = ["GPL-3.0"], name = "gpl-crate" },
]

# Uncomment and configure if you need to clarify licenses for specific crates:
# [[licenses.clarify]]
# crate = "ring"
# expression = "MIT AND ISC AND OpenSSL"
# license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
# Allow these workspace members to have multiple versions
allow = []
# Deny these crates entirely
deny = [
    # Example: { name = "openssl" },
]
# Skip checking these crates and their dependencies
skip = []
# Skip this crate from being checked for multiple versions
skip-tree = []

[sources]
# Deny crates from unknown registries or git sources
unknown-registry = "deny"
unknown-git = "warn"
# Allow only these git sources
allow-git = []
# Allow crates only from these registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
